services:
  pydocument-server:
    container_name: pydocument-server
    ports:
      - 8010:8000
    build:
      context: ../sidecar/pdf-ingestion
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    name: medibrain_app-network
